#!/usr/bin/env bash
# Pager one-shot installer for Ubuntu 22.04+/24.04.
#
# Installs Docker Engine + the compose plugin from the official Docker apt
# repo and the go-task task runner, clones this repo if needed, generates a
# random admin password and session pepper into .env, and brings the stack
# up with `docker compose`.
#
# Idempotent: on subsequent runs the existing .env is preserved and only
# `docker compose up` is repeated. Delete .env manually if you want fresh
# credentials.
#
# Usage — from a fresh clone:
#   sudo ./scripts/install.sh --domain pager.example.com --email you@example.com
#
# Or one-liner (the script clones for you into /opt/pager):
#   curl -fsSL https://raw.githubusercontent.com/vikar-ltd/pager/main/scripts/install.sh \
#     | sudo bash -s -- --domain pager.example.com --email you@example.com
#
# Flags:
#   --domain <host>     Public hostname for the admin UI (required)
#   --email  <addr>     Email for Let's Encrypt registration (required)
#   --username <name>   Root username to seed (default: root)
#   --dir  <path>       Install dir (default: /opt/pager)
#   --repo <url>        Git remote if the script has to clone
#   --yes               Non-interactive; fail if --domain / --email are missing
#   -h, --help          Show this help

set -euo pipefail

REPO_URL="${PAGER_REPO_URL:-https://github.com/vikar-ltd/pager.git}"
INSTALL_DIR="${PAGER_INSTALL_DIR:-/opt/pager}"
ROOT_USERNAME="${PAGER_ROOT_USERNAME:-root}"
DOMAIN=""
EMAIL=""
NONINTERACTIVE=0

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mx\033[0m %s\n' "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
	case "$1" in
		--domain)   DOMAIN="$2"; shift 2 ;;
		--email)    EMAIL="$2"; shift 2 ;;
		--username) ROOT_USERNAME="$2"; shift 2 ;;
		--dir)      INSTALL_DIR="$2"; shift 2 ;;
		--repo)     REPO_URL="$2"; shift 2 ;;
		--yes|-y)   NONINTERACTIVE=1; shift ;;
		-h|--help)
			sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'
			exit 0 ;;
		*) die "unknown argument: $1 (see --help)" ;;
	esac
done

[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "run as root (sudo)"

if ! grep -qi ubuntu /etc/os-release 2>/dev/null; then
	warn "this installer targets Ubuntu — proceeding anyway"
fi

prompt_if_missing() {
	local var=$1 label=$2
	if [[ -z "${!var}" ]]; then
		if [[ "$NONINTERACTIVE" -eq 1 ]]; then
			die "$label required (pass --$(echo "$var" | tr '[:upper:]' '[:lower:]'))"
		fi
		read -r -p "$label: " "$var"
	fi
}

prompt_if_missing DOMAIN "Public hostname for the Pager admin UI (e.g. pager.example.com)"
prompt_if_missing EMAIL  "Email for Let's Encrypt notifications"

# ---- prerequisites: git + docker + compose plugin
if ! command -v git >/dev/null 2>&1; then
	log "installing git"
	apt-get update -y
	apt-get install -y git
fi

if ! command -v docker >/dev/null 2>&1; then
	log "installing Docker Engine + compose plugin"
	apt-get update -y
	apt-get install -y ca-certificates curl gnupg
	install -m 0755 -d /etc/apt/keyrings
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
		| gpg --dearmor -o /etc/apt/keyrings/docker.gpg
	chmod a+r /etc/apt/keyrings/docker.gpg
	UBU_CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
	echo \
		"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $UBU_CODENAME stable" \
		> /etc/apt/sources.list.d/docker.list
	apt-get update -y
	apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
	systemctl enable --now docker
fi

if ! docker compose version >/dev/null 2>&1; then
	die "docker compose plugin not available after install — check apt logs"
fi

# ---- task runner (https://taskfile.dev) — enables `task update`, `task backup`, etc.
if ! command -v task >/dev/null 2>&1; then
	log "installing go-task"
	curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b /usr/local/bin >/dev/null
fi

# ---- source checkout
if [[ ! -d "$INSTALL_DIR/.git" ]]; then
	log "cloning $REPO_URL into $INSTALL_DIR"
	git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# ---- .env
ENV_FILE="$INSTALL_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
	log "generating $ENV_FILE"
	# Use openssl instead of `tr </dev/urandom | head -c N`: under
	# `set -euo pipefail`, head closing its stdin gives tr a SIGPIPE
	# (exit 141) which surfaces as a pipeline failure and aborts the whole
	# install before we ever get to write .env. openssl is a hard dep of
	# ca-certificates + curl so it's always present.
	ROOT_PASSWORD=$(openssl rand -hex 16)   # 32 hex chars
	SESSION_PEPPER=$(openssl rand -hex 24)  # 48 hex chars
	umask 077
	cat > "$ENV_FILE" <<EOF
# generated by scripts/install.sh — chmod 600
PAGER_DOMAIN=$DOMAIN
ACME_EMAIL=$EMAIL
ROOT_USERNAME=$ROOT_USERNAME
ROOT_PASSWORD=$ROOT_PASSWORD
MONGO_URI=mongodb://mongo:27017
MONGO_DB=pager
SESSION_PEPPER=$SESSION_PEPPER
EOF
else
	log "keeping existing $ENV_FILE"
fi

# ---- bring the stack up
log "bringing up the stack"
docker compose pull 2>/dev/null || true
docker compose up -d --build

# ---- wait for API health
log "waiting for API to come up (timeout 60s)"
for i in $(seq 1 60); do
	if docker compose exec -T api /pager -healthcheck >/dev/null 2>&1; then
		break
	fi
	sleep 1
	if [[ "$i" -eq 60 ]]; then
		warn "API didn't come healthy in 60s — check 'docker compose logs api'"
	fi
done

# shellcheck disable=SC1090
source "$ENV_FILE"

cat <<EOF

===================================================================
  Pager is up.

  URL:      https://$PAGER_DOMAIN
  Username: $ROOT_USERNAME
  Password: $ROOT_PASSWORD

  Credentials live in $ENV_FILE (mode 600). Store them somewhere
  safe — the password isn't retrievable later, only re-generatable.

  Next steps:
    1. Sign in at the URL above.
    2. Create a Property, copy its snippet into your site.
    3. Watch the visitor timeline populate.

  Useful commands (run from $INSTALL_DIR):
    task -l              # list all recipes
    task update          # pull latest code and rebuild the stack
    task status          # container status
    task logs:api        # tail API logs
    task logs:caddy      # tail Caddy / TLS logs
    task backup          # dump the pager db to ./backups/
    task mongo           # open a mongosh shell

  Under the hood these are thin wrappers around docker compose — run
  \`cat Taskfile.yml\` if you want to see what each recipe does.
===================================================================
EOF
