#!/usr/bin/env bash
# Pager one-shot installer for Ubuntu 22.04+/24.04.
#
# Installs Docker Engine + the compose plugin from the official Docker apt
# repo, clones this repo if needed, generates a random admin password and
# session pepper into .env, and brings the stack up with `docker compose`.
#
# Idempotent: on subsequent runs the existing .env is preserved and only
# `docker compose up` is repeated. Delete .env manually if you want fresh
# credentials.
#
# Usage — from a fresh clone:
#   sudo ./scripts/install.sh --domain pager.example.com --email you@example.com
#
# Or one-liner (the script clones for you into /opt/pager):
#   curl -fsSL https://raw.githubusercontent.com/vikar-ltd/pager/main/scripts/install.sh \
#     | sudo bash -s -- --domain pager.example.com --email you@example.com
#
# Flags:
#   --domain <host>     Public hostname for the admin UI (required)
#   --email  <addr>     Email for Let's Encrypt registration (required)
#   --username <name>   Admin username (default: admin)
#   --dir  <path>       Install dir (default: /opt/pager)
#   --repo <url>        Git remote if the script has to clone
#   --yes               Non-interactive; fail if --domain / --email are missing
#   -h, --help          Show this help

set -euo pipefail

REPO_URL="${PAGER_REPO_URL:-https://github.com/vikar-ltd/pager.git}"
INSTALL_DIR="${PAGER_INSTALL_DIR:-/opt/pager}"
ADMIN_USERNAME="${PAGER_ADMIN_USERNAME:-admin}"
DOMAIN=""
EMAIL=""
NONINTERACTIVE=0

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mx\033[0m %s\n' "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
	case "$1" in
		--domain)   DOMAIN="$2"; shift 2 ;;
		--email)    EMAIL="$2"; shift 2 ;;
		--username) ADMIN_USERNAME="$2"; shift 2 ;;
		--dir)      INSTALL_DIR="$2"; shift 2 ;;
		--repo)     REPO_URL="$2"; shift 2 ;;
		--yes|-y)   NONINTERACTIVE=1; shift ;;
		-h|--help)
			sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'
			exit 0 ;;
		*) die "unknown argument: $1 (see --help)" ;;
	esac
done

[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "run as root (sudo)"

if ! grep -qi ubuntu /etc/os-release 2>/dev/null; then
	warn "this installer targets Ubuntu — proceeding anyway"
fi

prompt_if_missing() {
	local var=$1 label=$2
	if [[ -z "${!var}" ]]; then
		if [[ "$NONINTERACTIVE" -eq 1 ]]; then
			die "$label required (pass --$(echo "$var" | tr '[:upper:]' '[:lower:]'))"
		fi
		read -r -p "$label: " "$var"
	fi
}

prompt_if_missing DOMAIN "Public hostname for the Pager admin UI (e.g. pager.example.com)"
prompt_if_missing EMAIL  "Email for Let's Encrypt notifications"

# ---- prerequisites: git + docker + compose plugin
if ! command -v git >/dev/null 2>&1; then
	log "installing git"
	apt-get update -y
	apt-get install -y git
fi

if ! command -v docker >/dev/null 2>&1; then
	log "installing Docker Engine + compose plugin"
	apt-get update -y
	apt-get install -y ca-certificates curl gnupg
	install -m 0755 -d /etc/apt/keyrings
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
		| gpg --dearmor -o /etc/apt/keyrings/docker.gpg
	chmod a+r /etc/apt/keyrings/docker.gpg
	UBU_CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
	echo \
		"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $UBU_CODENAME stable" \
		> /etc/apt/sources.list.d/docker.list
	apt-get update -y
	apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
	systemctl enable --now docker
fi

if ! docker compose version >/dev/null 2>&1; then
	die "docker compose plugin not available after install — check apt logs"
fi

# ---- source checkout
if [[ ! -d "$INSTALL_DIR/.git" ]]; then
	log "cloning $REPO_URL into $INSTALL_DIR"
	git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# ---- .env
ENV_FILE="$INSTALL_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
	log "generating $ENV_FILE"
	rand() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$1"; }
	ADMIN_PASSWORD=$(rand 32)
	SESSION_PEPPER=$(rand 48)
	umask 077
	cat > "$ENV_FILE" <<EOF
# generated by scripts/install.sh — chmod 600
PAGER_DOMAIN=$DOMAIN
ACME_EMAIL=$EMAIL
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_PASSWORD
MONGO_URI=mongodb://mongo:27017
MONGO_DB=pager
SESSION_PEPPER=$SESSION_PEPPER
EOF
else
	log "keeping existing $ENV_FILE"
fi

# ---- bring the stack up
log "bringing up the stack"
docker compose pull 2>/dev/null || true
docker compose up -d --build

# ---- wait for API health
log "waiting for API to come up (timeout 60s)"
for i in $(seq 1 60); do
	if docker compose exec -T api /pager -healthcheck >/dev/null 2>&1; then
		break
	fi
	sleep 1
	if [[ "$i" -eq 60 ]]; then
		warn "API didn't come healthy in 60s — check 'docker compose logs api'"
	fi
done

# shellcheck disable=SC1090
source "$ENV_FILE"

cat <<EOF

===================================================================
  Pager is up.

  URL:      https://$PAGER_DOMAIN
  Username: $ADMIN_USERNAME
  Password: $ADMIN_PASSWORD

  Credentials live in $ENV_FILE (mode 600). Store them somewhere
  safe — the password isn't retrievable later, only re-generatable.

  Next steps:
    1. Sign in at the URL above.
    2. Create a Property, copy its snippet into your site.
    3. Watch the visitor timeline populate.

  Useful commands (run from $INSTALL_DIR):
    docker compose logs -f api      # tail API logs
    docker compose ps               # container status
    docker compose down             # stop everything
    docker compose pull && docker compose up -d --build  # upgrade
===================================================================
EOF
